    sia_7f_arm : 
    # Publish all joint states -----------------------------------
      joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 10

    # Position Controllers ---------------------------------------
    sia_7f_joint1_position_controller : 
      type: position_controllers/JointPositionController
      joint: sia_7f_joint1
      pid: {p: 1.0, i: 1.0, d: 0.0}

    sia_7f_joint2_position_controller : 
      type: position_controllers/JointPositionController
      joint: sia_7f_joint2
      pid: {p: 1.0, i: 1.0, d: 0.0}

    sia_7f_joint3_position_controller : 
      type: position_controllers/JointPositionController
      joint: sia_7f_joint3
      pid: {p: 1.0, i: 1.0, d: 0.0}
   
    sia_7f_joint4_position_controller : 
      type: position_controllers/JointPositionController
      joint: sia_7f_joint4
      pid: {p: 1.0, i: 1.0, d: 0.0}

    sia_7f_joint5_position_controller : 
      type: position_controllers/JointPositionController
      joint: sia_7f_joint5
      pid: {p: 1.0, i: 1.0, d: 0.0}
    
    sia_7f_gripper_position_controller : 
      type: position_controllers/JointPositionController
      joint: sia_7f_gripper_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}

