sia_7f_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: sia_7f_joint1
    pid: {p: 100000.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: sia_7f_joint2
    pid: {p: 100000.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: sia_7f_joint3
    pid: {p: 100000.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: sia_7f_joint4
    pid: {p: 100000.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: sia_7f_joint5
    pid: {p: 100000.0, i: 0.01, d: 10.0}
  gripper_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: sia_7f_gripper
    pid: {p: 100000.0, i: 0.01, d: 10.0}

  finger_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: sia_7f_finger_joint
    pid: {p: 100000.0, i: 0.01, d: 10.0}


 
