controller_list:
  - name: fake_arm_controller
    joints:
      - sia_7f_joint1
      - sia_7f_joint2
      - sia_7f_joint3
      - sia_7f_joint4
      - sia_7f_joint5
      - sia_7f_gripper
  - name: fake_gripper_controller
    joints:
      - sia_7f_finger_joint